plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

Style/Documentation:
  Enabled: false

StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: diff_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: diff_comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/SymbolArray:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/ImplicitBlockExpectation:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/routes.rb"

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
